"""Import car_dataset.csv into the existing PostgreSQL cars table."""

import os
import re
from io import StringIO

import pandas as pd
import psycopg2
from dotenv import load_dotenv

load_dotenv()

CSV_PATH = os.getenv("CSV_PATH", r"C:\Users\ansha\Downloads\car_dataset.csv")

COLUMN_MAP = {
    "Make": "make",
    "Model": "model",
    "Variant": "variant",
    "Ex-Showroom_Price": "ex_showroom_price",
    "Displacement": "displacement",
    "Cylinders": "cylinders",
    "Fuel_Tank_Capacity": "fuel_tank_capacity",
    "Fuel_Type": "fuel_type",
    "Height": "height",
    "Length": "length",
    "Width": "width",
    "Body_Type": "body_type",
    "Seating_Capacity": "seating_capacity",
    "Type": "transmission",
    "Power.1": "power",
    "Torque.1": "torque",
}

INSERT_COLUMNS = list(COLUMN_MAP.values())

CREATE_CARS_TABLE = """
CREATE TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    variant VARCHAR(150),
    ex_showroom_price NUMERIC(12, 2),
    displacement NUMERIC(10, 2),
    cylinders SMALLINT,
    fuel_tank_capacity NUMERIC(6, 2),
    fuel_type VARCHAR(50),
    height NUMERIC(8, 2),
    length NUMERIC(8, 2),
    width NUMERIC(8, 2),
    body_type VARCHAR(50),
    seating_capacity SMALLINT,
    transmission VARCHAR(50),
    power NUMERIC(8, 2),
    torque NUMERIC(8, 2)
);
"""


def db_connect():
    return psycopg2.connect(
        host=os.getenv("PGHOST", "localhost"),
        port=os.getenv("PGPORT", "5432"),
        user=os.getenv("PGUSER", "postgres"),
        password=os.getenv("PGPASSWORD", ""),
        dbname=os.getenv("PGDATABASE", "carworld"),
    )


def clean_price(value):
    if pd.isna(value) or value == "":
        return None
    text = str(value)
    text = text.replace("₹", "").replace(",", "").strip()
    text = re.sub(r"[^\d.]", "", text)
    if text == "":
        return None
    return round(float(text), 2)


def prepare_dataframe(csv_path):
    df = pd.read_csv(csv_path)
    missing = [col for col in COLUMN_MAP if col not in df.columns]
    if missing:
        raise SystemExit(f"CSV is missing columns: {missing}")

    df = df[list(COLUMN_MAP.keys())].rename(columns=COLUMN_MAP)
    df["ex_showroom_price"] = df["ex_showroom_price"].map(clean_price)

    numeric_cols = [
        "displacement",
        "fuel_tank_capacity",
        "height",
        "length",
        "width",
        "power",
        "torque",
    ]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    for col in ["cylinders", "seating_capacity"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

    for col in ["make", "model", "variant", "fuel_type", "body_type", "transmission"]:
        df[col] = df[col].astype(str).str.strip()
        df.loc[df[col].isin(["", "nan", "None"]), col] = None

    return df


def copy_rows(cursor, df):
    buffer = StringIO()
    df[INSERT_COLUMNS].to_csv(buffer, index=False, header=False, na_rep="\\N")
    buffer.seek(0)
    cursor.copy_expert(
        sql=(
            "COPY cars ("
            + ", ".join(INSERT_COLUMNS)
            + ") FROM STDIN WITH (FORMAT CSV, NULL '\\N')"
        ),
        file=buffer,
    )


def verify(cursor):
    cursor.execute("SELECT COUNT(*) FROM cars;")
    total = cursor.fetchone()[0]
    print(f"Total row count: {total}")

    cursor.execute(
        """
        SELECT id, make, model, variant, ex_showroom_price
        FROM cars
        ORDER BY id
        LIMIT 5;
        """
    )
    print("\nFirst 5 rows:")
    for row in cursor.fetchall():
        print(row)

    cursor.execute(
        """
        SELECT make, COUNT(*) AS n
        FROM cars
        GROUP BY make
        ORDER BY n DESC
        LIMIT 8;
        """
    )
    print("\nSample makes:")
    for row in cursor.fetchall():
        print(f"  {row[0]}: {row[1]}")

    cursor.execute(
        """
        SELECT MIN(ex_showroom_price), MAX(ex_showroom_price)
        FROM cars;
        """
    )
    min_price, max_price = cursor.fetchone()
    print(f"\nMinimum price: {min_price}")
    print(f"Maximum price: {max_price}")


def main():
    df = prepare_dataframe(CSV_PATH)
    print(f"Read {len(df)} rows from {CSV_PATH}")

    conn = db_connect()
    try:
        with conn:
            with conn.cursor() as cursor:
                cursor.execute(CREATE_CARS_TABLE)
                copy_rows(cursor, df)
        with conn.cursor() as cursor:
            verify(cursor)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
